# Simple workflow for deploying static content to GitHub Pages
name: Build and deploy static html pages for the SP exercises

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-htmls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pypandoc

      - name: Install xelatex
        run: sudo apt-get update && sudo apt-get install -y texlive-xetex

      - name: Run create_files.py
        run: python create_files.py

      - name: Create index files
        run: python create_index_pages.py

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-html
          path: output/output_html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-htmls
    steps:
      - name: Download HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: output-html
          path: created_htmls
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Check HTML output
        run: ls -l created_htmls
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'created_htmls'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
